# Generated by Django 3.1.3 on 2020-11-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('dateOfBirth', models.DateField()),
                ('login', models.CharField(max_length=30, unique=True)),
                ('isDeleted', models.CharField(choices=[('T', 'True'), ('F', 'False')], default='F', max_length=1)),
            ],
        ),
    ]
